### ISSUE TITLE
Roadmap: Integrate Color-picker for Customization

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/obsidian-gistr#10]
# Summary
- [x] Add npm dependency **Pickr** - [simonwep/pickr](https://www.npmjs.com/package/@simonwep/pickr)
- [x] Add color-picker to plugin settings
- [x] Removal of deprecated color textfield

---

# Details
Added standard color picker for initial release - de5bf88
Enhanced color picker scheduled for v1.1.0
