### ISSUE TITLE
🗺️ Roadmap: Roadmap: OpenGist Integration

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/obsidian-gistr#13]
# Summary
OpenGist integration works well, however, the way gists are displayed could be better.  Currently working with the OpenGist developer to make revisions to his HTML / CSS so that gists display in a similar fashion to Github.

At present, this plugin had to introduce custom edits to make gists for OpenGist look better. Topic areas are:
- Header background of gist can cut off if the user has a gist which scrolls horizontally (applied plugin-side fix)
- Applied custom CSS properties to ensure the gist snippet background color continues past the Obsidian frame for the gist.

While the plugin has fixes to address these, this should really be handled by OpenGIst to make for a more seamless integration.

---

# Objectives
- [x] Move gist snippet details to footer of embedded gist (filename, view raw button, etc)
- [x] Migrate scrollbar to separate gist snippet and gist footer
- [x] Paint scrollbar with CSS
  - Scrollbar should be thinner, and customizable by user depending on the theme selected.
