### ISSUE TITLE
Roadmap: Ability to Get & Save gists from Obsidian

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/obsidian-gistr#18]
# Summary
Give users the ability to get and save Github gists directly from Obsidian
- [x] Implement Github API Token configuration
- [x] Add right-click **Save Gist** menu item
- [x] (Autosave) Allow updating gists after creation
- [x] Support public gists
- [x] Support private gists
