### ISSUE TITLE
Roadmap: Github Repo Integration

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/obsidian-gistr#30]
## Summary
Now that gists have been fully integrated; regular Github repos should be focused on now in order to develop a single plugin which takes care of all aspects of Github.

<br />

---

<br />

## Tasks
-[ ] Allow user to push their vault to a Github repo
  - [ ] Public
  - [ ] Private
- [ ] Honor `.gitignore` file to exclude certain files from being pushed
- [ ] Support specifying a commit message for each push
- [ ] Support autosaving vault notes to repo
