### ISSUE TITLE
Roadmap: Change codeblock syntax

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/obsidian-gistr#41]
## Summary
Gist codeblock syntax to be modified and move away from an individual URL to a codeblock that supports property names and values.

<br />

---

<br />

## Tasks
- [x] Add new regex pattern with matching groups
- [x] Revise methods to utilize new pattern
- [x] Allow for regular URL without properties / values

<br />

---

<br />

## Example
````
```gistr
url:          https://path/to/username/gist_id
background:   https://path/to/image.png
theme:        dark
```
````
