### ISSUE TITLE
Roadmap: Dark Theme Support [Github]

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/obsidian-gistr#9]
# Tasks
- [x] Add dark mode support for Github via plugin settings.
  - [x] dba31ec
- [x] Add theme selector to plugin settings
- [x] Add scrollbar painting similar to #13

---

# Details
While Github and OpenGist share the same structure, both handle styling completely different. Introduce a new set of functions to allow users to display their gists using a dark theme.
